enableGlobalCache: false

httpProxy: "http://127.0.0.1:1081"

httpsProxy: "http://127.0.0.1:1081"

nodeLinker: node-modules

npmRegistryServer: "https://registry.npm.taobao.org"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

preferInteractive: true

yarnPath: .yarn/releases/yarn-2.4.1.cjs
